/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as crossChainCrowdfundSol from "./CrossChainCrowdfund.sol";
export { GiveHubUniversal__factory } from "./GiveHubUniversal__factory";
