/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWZETA,
  IWZETAInterface,
} from "../../../contracts/CrossChainCrowdfund.sol/IWZETA";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWZETA__factory {
  static readonly abi = _abi;
  static createInterface(): IWZETAInterface {
    return new Interface(_abi) as IWZETAInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IWZETA {
    return new Contract(address, _abi, runner) as unknown as IWZETA;
  }
}
