/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OwnableLite,
  OwnableLiteInterface,
} from "../../../contracts/CrossChainCrowdfund.sol/OwnableLite";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "prev",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "next",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "n",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class OwnableLite__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableLiteInterface {
    return new Interface(_abi) as OwnableLiteInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OwnableLite {
    return new Contract(address, _abi, runner) as unknown as OwnableLite;
  }
}
