/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type MessageContextStruct = {
  sender: BytesLike;
  senderEVM: AddressLike;
  chainID: BigNumberish;
};

export type MessageContextStructOutput = [
  sender: string,
  senderEVM: string,
  chainID: bigint
] & { sender: string; senderEVM: string; chainID: bigint };

export type RevertContextStruct = {
  sender: AddressLike;
  asset: AddressLike;
  amount: BigNumberish;
  revertMessage: BytesLike;
};

export type RevertContextStructOutput = [
  sender: string,
  asset: string,
  amount: bigint,
  revertMessage: string
] & { sender: string; asset: string; amount: bigint; revertMessage: string };

export declare namespace GiveHubUniversal {
  export type CampaignStruct = {
    id: BigNumberish;
    creator: AddressLike;
    payoutToken: AddressLike;
    payoutChainId: BigNumberish;
    payoutAddress: AddressLike;
    raised: BigNumberish;
    goal: BigNumberish;
    active: boolean;
  };

  export type CampaignStructOutput = [
    id: bigint,
    creator: string,
    payoutToken: string,
    payoutChainId: bigint,
    payoutAddress: string,
    raised: bigint,
    goal: bigint,
    active: boolean
  ] & {
    id: bigint;
    creator: string;
    payoutToken: string;
    payoutChainId: bigint;
    payoutAddress: string;
    raised: bigint;
    goal: bigint;
    active: boolean;
  };

  export type ContributionStruct = {
    campaignId: BigNumberish;
    donor: AddressLike;
    amount: BigNumberish;
    token: AddressLike;
    originChain: string;
    timestamp: BigNumberish;
  };

  export type ContributionStructOutput = [
    campaignId: bigint,
    donor: string,
    amount: bigint,
    token: string,
    originChain: string,
    timestamp: bigint
  ] & {
    campaignId: bigint;
    donor: string;
    amount: bigint;
    token: string;
    originChain: string;
    timestamp: bigint;
  };
}

export interface GiveHubUniversalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "campaignContributions"
      | "campaigns"
      | "closeCampaign"
      | "createCampaign"
      | "donateDirectly"
      | "gateway"
      | "getCampaign"
      | "getContributions"
      | "nextCampaignId"
      | "onCall"
      | "onRevert"
      | "updatePayoutConfig"
      | "withdrawToCreator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "ContributionReceived"
      | "PayoutInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "campaignContributions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "donateDirectly",
    values: [BigNumberish, AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCampaignId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onCall",
    values: [MessageContextStruct, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onRevert",
    values: [RevertContextStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePayoutConfig",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToCreator",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donateDirectly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCampaignId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onRevert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePayoutConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToCreator",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    goal: BigNumberish,
    payoutToken: AddressLike,
    payoutChainId: BigNumberish,
    payoutAddress: AddressLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    goal: bigint,
    payoutToken: string,
    payoutChainId: bigint,
    payoutAddress: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    goal: bigint;
    payoutToken: string;
    payoutChainId: bigint;
    payoutAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    contributionId: BigNumberish,
    originalToken: AddressLike,
    originalAmount: BigNumberish,
    convertedAmount: BigNumberish,
    originChain: string,
    donorName: string,
    note: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    contributionId: bigint,
    originalToken: string,
    originalAmount: bigint,
    convertedAmount: bigint,
    originChain: string,
    donorName: string,
    note: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    contributionId: bigint;
    originalToken: string;
    originalAmount: bigint;
    convertedAmount: bigint;
    originChain: string;
    donorName: string;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutInitiatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    destinationChainId: BigNumberish,
    destinationAddress: AddressLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    amount: bigint,
    destinationChainId: bigint,
    destinationAddress: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    amount: bigint;
    destinationChainId: bigint;
    destinationAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GiveHubUniversal extends BaseContract {
  connect(runner?: ContractRunner | null): GiveHubUniversal;
  waitForDeployment(): Promise<this>;

  interface: GiveHubUniversalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  campaignContributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        token: string;
        originChain: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        payoutToken: string;
        payoutChainId: bigint;
        payoutAddress: string;
        raised: bigint;
        goal: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  closeCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      _goal: BigNumberish,
      _payoutToken: AddressLike,
      _payoutChainId: BigNumberish,
      _payoutAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  donateDirectly: TypedContractMethod<
    [
      campaignId: BigNumberish,
      zrc20Token: AddressLike,
      amount: BigNumberish,
      donorName: string,
      note: string
    ],
    [void],
    "nonpayable"
  >;

  gateway: TypedContractMethod<[], [string], "view">;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [GiveHubUniversal.CampaignStructOutput],
    "view"
  >;

  getContributions: TypedContractMethod<
    [campaignId: BigNumberish],
    [GiveHubUniversal.ContributionStructOutput[]],
    "view"
  >;

  nextCampaignId: TypedContractMethod<[], [bigint], "view">;

  onCall: TypedContractMethod<
    [
      context: MessageContextStruct,
      zrc20: AddressLike,
      amount: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  onRevert: TypedContractMethod<
    [revertContext: RevertContextStruct],
    [void],
    "nonpayable"
  >;

  updatePayoutConfig: TypedContractMethod<
    [
      campaignId: BigNumberish,
      newPayoutToken: AddressLike,
      newPayoutChainId: BigNumberish,
      newPayoutAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  withdrawToCreator: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "campaignContributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, bigint] & {
        campaignId: bigint;
        donor: string;
        amount: bigint;
        token: string;
        originChain: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        payoutToken: string;
        payoutChainId: bigint;
        payoutAddress: string;
        raised: bigint;
        goal: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _goal: BigNumberish,
      _payoutToken: AddressLike,
      _payoutChainId: BigNumberish,
      _payoutAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donateDirectly"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      zrc20Token: AddressLike,
      amount: BigNumberish,
      donorName: string,
      note: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [GiveHubUniversal.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributions"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [GiveHubUniversal.ContributionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCampaignId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onCall"
  ): TypedContractMethod<
    [
      context: MessageContextStruct,
      zrc20: AddressLike,
      amount: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onRevert"
  ): TypedContractMethod<
    [revertContext: RevertContextStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePayoutConfig"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      newPayoutToken: AddressLike,
      newPayoutChainId: BigNumberish,
      newPayoutAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToCreator"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutInitiated"
  ): TypedContractEvent<
    PayoutInitiatedEvent.InputTuple,
    PayoutInitiatedEvent.OutputTuple,
    PayoutInitiatedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,uint256,address,uint256,address)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "ContributionReceived(uint256,address,uint256,address,uint256,uint256,string,string,string)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "PayoutInitiated(uint256,address,uint256,uint256,address)": TypedContractEvent<
      PayoutInitiatedEvent.InputTuple,
      PayoutInitiatedEvent.OutputTuple,
      PayoutInitiatedEvent.OutputObject
    >;
    PayoutInitiated: TypedContractEvent<
      PayoutInitiatedEvent.InputTuple,
      PayoutInitiatedEvent.OutputTuple,
      PayoutInitiatedEvent.OutputObject
    >;
  };
}
