/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainCrowdfundSol from "./CrossChainCrowdfund.sol";
export type { crossChainCrowdfundSol };
export type { GiveHubUniversal } from "./GiveHubUniversal";
