/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  BytesHelperLib,
  BytesHelperLibInterface,
} from "../../../../@zetachain/toolkit/contracts/BytesHelperLib";

const _abi = [
  {
    inputs: [],
    name: "OffsetOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212208c54197d6b4cc1d27bfa41c3dfa2caf535be443a844aa727a4e242aeec2464b664736f6c634300081a0033";

type BytesHelperLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BytesHelperLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BytesHelperLib__factory extends ContractFactory {
  constructor(...args: BytesHelperLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BytesHelperLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BytesHelperLib__factory {
    return super.connect(runner) as BytesHelperLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BytesHelperLibInterface {
    return new Interface(_abi) as BytesHelperLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BytesHelperLib {
    return new Contract(address, _abi, runner) as unknown as BytesHelperLib;
  }
}
