/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type MessageContextStruct = {
  sender: BytesLike;
  senderEVM: AddressLike;
  chainID: BigNumberish;
};

export type MessageContextStructOutput = [
  sender: string,
  senderEVM: string,
  chainID: bigint
] & { sender: string; senderEVM: string; chainID: bigint };

export type RevertContextStruct = {
  sender: AddressLike;
  asset: AddressLike;
  amount: BigNumberish;
  revertMessage: BytesLike;
};

export type RevertContextStructOutput = [
  sender: string,
  asset: string,
  amount: bigint,
  revertMessage: string
] & { sender: string; asset: string; amount: bigint; revertMessage: string };

export declare namespace CrossChainCrowdfund {
  export type CampaignInfoStruct = {
    campaignId: BigNumberish;
    creator: AddressLike;
    preferredZRC20: AddressLike;
    active: boolean;
  };

  export type CampaignInfoStructOutput = [
    campaignId: bigint,
    creator: string,
    preferredZRC20: string,
    active: boolean
  ] & {
    campaignId: bigint;
    creator: string;
    preferredZRC20: string;
    active: boolean;
  };
}

export interface CrossChainCrowdfundInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WZETA"
      | "allowedInTokens"
      | "allowedOutTokens"
      | "btcZRC20"
      | "campaignStatus"
      | "campaigns"
      | "contributions"
      | "createCampaign"
      | "debug"
      | "donateNative"
      | "donateZRC20"
      | "ethZRC20"
      | "gateway"
      | "getAllSyncedCampaigns"
      | "getCampaignInfo"
      | "nextCampaignId"
      | "nextContributionId"
      | "onCall"
      | "onRevert"
      | "owner"
      | "rescueNative"
      | "rescueToken"
      | "router"
      | "setAllowedInToken"
      | "setAllowedOutToken"
      | "setCampaignCallMessage"
      | "setDebug"
      | "setSlippageBps"
      | "setTokenLabel"
      | "setUniswapRouter"
      | "slippageBps"
      | "tokenLabel"
      | "transferOwnership"
      | "updateCampaignDestination"
      | "updateCampaignPayoutToken"
      | "usdcZRC20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowedInTokenSet"
      | "AllowedOutTokenSet"
      | "CampaignCreated"
      | "ContributionReceived"
      | "DebugApprove"
      | "DebugApproveReset"
      | "DebugContributionRecorded"
      | "DebugDecodedDonate"
      | "DebugDonationBegin"
      | "DebugGasFee"
      | "DebugGatewayWithdraw"
      | "DebugOnCallEntered"
      | "DebugOnRevert"
      | "DebugRouterMissing"
      | "DebugRouterSet"
      | "DebugSwapFailed"
      | "DebugSwapFailedBytes"
      | "DebugSwapPlanned"
      | "DebugSwapSucceeded"
      | "DebugToggle"
      | "DebugTransferOut"
      | "OwnershipTransferred"
      | "Rescue"
      | "SlippageUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "WZETA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowedInTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedOutTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "btcZRC20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "campaignStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "debug", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "donateNative",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "donateZRC20",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "ethZRC20", values?: undefined): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllSyncedCampaigns",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCampaignId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextContributionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onCall",
    values: [MessageContextStruct, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onRevert",
    values: [RevertContextStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rescueNative",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAllowedInToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedOutToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignCallMessage",
    values: [BigNumberish, BytesLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setDebug", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setSlippageBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenLabel",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniswapRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slippageBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenLabel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignDestination",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignPayoutToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcZRC20", values?: undefined): string;

  decodeFunctionResult(functionFragment: "WZETA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedInTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedOutTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "btcZRC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debug", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donateNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donateZRC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ethZRC20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllSyncedCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCampaignId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextContributionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onRevert", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedInToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedOutToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignCallMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDebug", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenLabel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignPayoutToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcZRC20", data: BytesLike): Result;
}

export namespace AllowedInTokenSetEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedOutTokenSetEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    preferredZRC20: AddressLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    preferredZRC20: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    preferredZRC20: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    contributionId: BigNumberish,
    originalToken: AddressLike,
    originalAmount: BigNumberish,
    convertedAmount: BigNumberish,
    originChain: string,
    donorName: string,
    note: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    contributionId: bigint,
    originalToken: string,
    originalAmount: bigint,
    convertedAmount: bigint,
    originChain: string,
    donorName: string,
    note: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    contributionId: bigint;
    originalToken: string;
    originalAmount: bigint;
    convertedAmount: bigint;
    originChain: string;
    donorName: string;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugApproveEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugApproveResetEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugContributionRecordedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugDecodedDonateEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donorName: string,
    note: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donorName: string,
    note: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    donorName: string;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugDonationBeginEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    tokenIn: AddressLike,
    amountIn: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    tokenIn: string,
    amountIn: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    tokenIn: string;
    amountIn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugGasFeeEvent {
  export type InputTuple = [
    token: AddressLike,
    gasToken: AddressLike,
    gasFee: BigNumberish,
    gasLimit: BigNumberish,
    haveBalance: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    gasToken: string,
    gasFee: bigint,
    gasLimit: bigint,
    haveBalance: bigint
  ];
  export interface OutputObject {
    token: string;
    gasToken: string;
    gasFee: bigint;
    gasLimit: bigint;
    haveBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugGatewayWithdrawEvent {
  export type InputTuple = [
    receiverToken: AddressLike,
    amount: BigNumberish,
    withCall: boolean
  ];
  export type OutputTuple = [
    receiverToken: string,
    amount: bigint,
    withCall: boolean
  ];
  export interface OutputObject {
    receiverToken: string;
    amount: bigint;
    withCall: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugOnCallEnteredEvent {
  export type InputTuple = [
    originSender: BytesLike,
    originChainId: BigNumberish,
    zrc20In: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    originSender: string,
    originChainId: bigint,
    zrc20In: string,
    amount: bigint
  ];
  export interface OutputObject {
    originSender: string;
    originChainId: bigint;
    zrc20In: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugOnRevertEvent {
  export type InputTuple = [
    asset: AddressLike,
    amount: BigNumberish,
    revertMessage: BytesLike
  ];
  export type OutputTuple = [
    asset: string,
    amount: bigint,
    revertMessage: string
  ];
  export interface OutputObject {
    asset: string;
    amount: bigint;
    revertMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugRouterMissingEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugRouterSetEvent {
  export type InputTuple = [router: AddressLike];
  export type OutputTuple = [router: string];
  export interface OutputObject {
    router: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugSwapFailedEvent {
  export type InputTuple = [reason: string];
  export type OutputTuple = [reason: string];
  export interface OutputObject {
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugSwapFailedBytesEvent {
  export type InputTuple = [lowLevelData: BytesLike];
  export type OutputTuple = [lowLevelData: string];
  export interface OutputObject {
    lowLevelData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugSwapPlannedEvent {
  export type InputTuple = [
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    pathLen: BigNumberish
  ];
  export type OutputTuple = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    pathLen: bigint
  ];
  export interface OutputObject {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    pathLen: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugSwapSucceededEvent {
  export type InputTuple = [amountOut: BigNumberish];
  export type OutputTuple = [amountOut: bigint];
  export interface OutputObject {
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugToggleEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugTransferOutEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [prev: AddressLike, next: AddressLike];
  export type OutputTuple = [prev: string, next: string];
  export interface OutputObject {
    prev: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RescueEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlippageUpdatedEvent {
  export type InputTuple = [bps: BigNumberish];
  export type OutputTuple = [bps: bigint];
  export interface OutputObject {
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainCrowdfund extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainCrowdfund;
  waitForDeployment(): Promise<this>;

  interface: CrossChainCrowdfundInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WZETA: TypedContractMethod<[], [string], "view">;

  allowedInTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  allowedOutTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  btcZRC20: TypedContractMethod<[], [string], "view">;

  campaignStatus: TypedContractMethod<
    [campaignId: BigNumberish],
    [[boolean, boolean] & { exists: boolean; active: boolean }],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string, bigint, boolean, string] & {
        creator: string;
        preferredZRC20: string;
        active: boolean;
        payoutAddress: string;
        payoutGasLimit: bigint;
        useArbitraryCall: boolean;
        callMessage: string;
      }
    ],
    "view"
  >;

  contributions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        campaignId: bigint;
        donor: string;
        originalToken: string;
        zrc20Received: string;
        originalAmount: bigint;
        convertedAmount: bigint;
        originChainId: bigint;
        timestamp: bigint;
        originChainName: string;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [preferredZRC20: AddressLike],
    [bigint],
    "nonpayable"
  >;

  debug: TypedContractMethod<[], [boolean], "view">;

  donateNative: TypedContractMethod<
    [campaignId: BigNumberish, donorName: string, note: string],
    [void],
    "payable"
  >;

  donateZRC20: TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      campaignId: BigNumberish,
      donorName: string,
      note: string
    ],
    [void],
    "nonpayable"
  >;

  ethZRC20: TypedContractMethod<[], [string], "view">;

  gateway: TypedContractMethod<[], [string], "view">;

  getAllSyncedCampaigns: TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [
      [CrossChainCrowdfund.CampaignInfoStructOutput[], bigint] & {
        infos: CrossChainCrowdfund.CampaignInfoStructOutput[];
        nextStart: bigint;
      }
    ],
    "view"
  >;

  getCampaignInfo: TypedContractMethod<
    [campaignId: BigNumberish],
    [CrossChainCrowdfund.CampaignInfoStructOutput],
    "view"
  >;

  nextCampaignId: TypedContractMethod<[], [bigint], "view">;

  nextContributionId: TypedContractMethod<[], [bigint], "view">;

  onCall: TypedContractMethod<
    [
      context: MessageContextStruct,
      zrc20: AddressLike,
      amount: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  onRevert: TypedContractMethod<
    [revertContext: RevertContextStruct],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rescueNative: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rescueToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  router: TypedContractMethod<[], [string], "view">;

  setAllowedInToken: TypedContractMethod<
    [t: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setAllowedOutToken: TypedContractMethod<
    [t: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setCampaignCallMessage: TypedContractMethod<
    [campaignId: BigNumberish, message: BytesLike, useArbitrary: boolean],
    [void],
    "nonpayable"
  >;

  setDebug: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  setSlippageBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenLabel: TypedContractMethod<
    [token: AddressLike, label: string],
    [void],
    "nonpayable"
  >;

  setUniswapRouter: TypedContractMethod<
    [_router: AddressLike],
    [void],
    "nonpayable"
  >;

  slippageBps: TypedContractMethod<[], [bigint], "view">;

  tokenLabel: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [n: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCampaignDestination: TypedContractMethod<
    [
      campaignId: BigNumberish,
      payoutAddress: AddressLike,
      payoutGasLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateCampaignPayoutToken: TypedContractMethod<
    [campaignId: BigNumberish, newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcZRC20: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WZETA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowedInTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowedOutTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "btcZRC20"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaignStatus"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [[boolean, boolean] & { exists: boolean; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string, bigint, boolean, string] & {
        creator: string;
        preferredZRC20: string;
        active: boolean;
        payoutAddress: string;
        payoutGasLimit: bigint;
        useArbitraryCall: boolean;
        callMessage: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        campaignId: bigint;
        donor: string;
        originalToken: string;
        zrc20Received: string;
        originalAmount: bigint;
        convertedAmount: bigint;
        originChainId: bigint;
        timestamp: bigint;
        originChainName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<[preferredZRC20: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "debug"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "donateNative"
  ): TypedContractMethod<
    [campaignId: BigNumberish, donorName: string, note: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "donateZRC20"
  ): TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      campaignId: BigNumberish,
      donorName: string,
      note: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ethZRC20"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllSyncedCampaigns"
  ): TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [
      [CrossChainCrowdfund.CampaignInfoStructOutput[], bigint] & {
        infos: CrossChainCrowdfund.CampaignInfoStructOutput[];
        nextStart: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignInfo"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [CrossChainCrowdfund.CampaignInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCampaignId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextContributionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onCall"
  ): TypedContractMethod<
    [
      context: MessageContextStruct,
      zrc20: AddressLike,
      amount: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onRevert"
  ): TypedContractMethod<
    [revertContext: RevertContextStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rescueNative"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAllowedInToken"
  ): TypedContractMethod<
    [t: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedOutToken"
  ): TypedContractMethod<
    [t: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignCallMessage"
  ): TypedContractMethod<
    [campaignId: BigNumberish, message: BytesLike, useArbitrary: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDebug"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlippageBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenLabel"
  ): TypedContractMethod<
    [token: AddressLike, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUniswapRouter"
  ): TypedContractMethod<[_router: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slippageBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenLabel"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[n: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCampaignDestination"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      payoutAddress: AddressLike,
      payoutGasLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignPayoutToken"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcZRC20"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AllowedInTokenSet"
  ): TypedContractEvent<
    AllowedInTokenSetEvent.InputTuple,
    AllowedInTokenSetEvent.OutputTuple,
    AllowedInTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "AllowedOutTokenSet"
  ): TypedContractEvent<
    AllowedOutTokenSetEvent.InputTuple,
    AllowedOutTokenSetEvent.OutputTuple,
    AllowedOutTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "DebugApprove"
  ): TypedContractEvent<
    DebugApproveEvent.InputTuple,
    DebugApproveEvent.OutputTuple,
    DebugApproveEvent.OutputObject
  >;
  getEvent(
    key: "DebugApproveReset"
  ): TypedContractEvent<
    DebugApproveResetEvent.InputTuple,
    DebugApproveResetEvent.OutputTuple,
    DebugApproveResetEvent.OutputObject
  >;
  getEvent(
    key: "DebugContributionRecorded"
  ): TypedContractEvent<
    DebugContributionRecordedEvent.InputTuple,
    DebugContributionRecordedEvent.OutputTuple,
    DebugContributionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DebugDecodedDonate"
  ): TypedContractEvent<
    DebugDecodedDonateEvent.InputTuple,
    DebugDecodedDonateEvent.OutputTuple,
    DebugDecodedDonateEvent.OutputObject
  >;
  getEvent(
    key: "DebugDonationBegin"
  ): TypedContractEvent<
    DebugDonationBeginEvent.InputTuple,
    DebugDonationBeginEvent.OutputTuple,
    DebugDonationBeginEvent.OutputObject
  >;
  getEvent(
    key: "DebugGasFee"
  ): TypedContractEvent<
    DebugGasFeeEvent.InputTuple,
    DebugGasFeeEvent.OutputTuple,
    DebugGasFeeEvent.OutputObject
  >;
  getEvent(
    key: "DebugGatewayWithdraw"
  ): TypedContractEvent<
    DebugGatewayWithdrawEvent.InputTuple,
    DebugGatewayWithdrawEvent.OutputTuple,
    DebugGatewayWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "DebugOnCallEntered"
  ): TypedContractEvent<
    DebugOnCallEnteredEvent.InputTuple,
    DebugOnCallEnteredEvent.OutputTuple,
    DebugOnCallEnteredEvent.OutputObject
  >;
  getEvent(
    key: "DebugOnRevert"
  ): TypedContractEvent<
    DebugOnRevertEvent.InputTuple,
    DebugOnRevertEvent.OutputTuple,
    DebugOnRevertEvent.OutputObject
  >;
  getEvent(
    key: "DebugRouterMissing"
  ): TypedContractEvent<
    DebugRouterMissingEvent.InputTuple,
    DebugRouterMissingEvent.OutputTuple,
    DebugRouterMissingEvent.OutputObject
  >;
  getEvent(
    key: "DebugRouterSet"
  ): TypedContractEvent<
    DebugRouterSetEvent.InputTuple,
    DebugRouterSetEvent.OutputTuple,
    DebugRouterSetEvent.OutputObject
  >;
  getEvent(
    key: "DebugSwapFailed"
  ): TypedContractEvent<
    DebugSwapFailedEvent.InputTuple,
    DebugSwapFailedEvent.OutputTuple,
    DebugSwapFailedEvent.OutputObject
  >;
  getEvent(
    key: "DebugSwapFailedBytes"
  ): TypedContractEvent<
    DebugSwapFailedBytesEvent.InputTuple,
    DebugSwapFailedBytesEvent.OutputTuple,
    DebugSwapFailedBytesEvent.OutputObject
  >;
  getEvent(
    key: "DebugSwapPlanned"
  ): TypedContractEvent<
    DebugSwapPlannedEvent.InputTuple,
    DebugSwapPlannedEvent.OutputTuple,
    DebugSwapPlannedEvent.OutputObject
  >;
  getEvent(
    key: "DebugSwapSucceeded"
  ): TypedContractEvent<
    DebugSwapSucceededEvent.InputTuple,
    DebugSwapSucceededEvent.OutputTuple,
    DebugSwapSucceededEvent.OutputObject
  >;
  getEvent(
    key: "DebugToggle"
  ): TypedContractEvent<
    DebugToggleEvent.InputTuple,
    DebugToggleEvent.OutputTuple,
    DebugToggleEvent.OutputObject
  >;
  getEvent(
    key: "DebugTransferOut"
  ): TypedContractEvent<
    DebugTransferOutEvent.InputTuple,
    DebugTransferOutEvent.OutputTuple,
    DebugTransferOutEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Rescue"
  ): TypedContractEvent<
    RescueEvent.InputTuple,
    RescueEvent.OutputTuple,
    RescueEvent.OutputObject
  >;
  getEvent(
    key: "SlippageUpdated"
  ): TypedContractEvent<
    SlippageUpdatedEvent.InputTuple,
    SlippageUpdatedEvent.OutputTuple,
    SlippageUpdatedEvent.OutputObject
  >;

  filters: {
    "AllowedInTokenSet(address,bool)": TypedContractEvent<
      AllowedInTokenSetEvent.InputTuple,
      AllowedInTokenSetEvent.OutputTuple,
      AllowedInTokenSetEvent.OutputObject
    >;
    AllowedInTokenSet: TypedContractEvent<
      AllowedInTokenSetEvent.InputTuple,
      AllowedInTokenSetEvent.OutputTuple,
      AllowedInTokenSetEvent.OutputObject
    >;

    "AllowedOutTokenSet(address,bool)": TypedContractEvent<
      AllowedOutTokenSetEvent.InputTuple,
      AllowedOutTokenSetEvent.OutputTuple,
      AllowedOutTokenSetEvent.OutputObject
    >;
    AllowedOutTokenSet: TypedContractEvent<
      AllowedOutTokenSetEvent.InputTuple,
      AllowedOutTokenSetEvent.OutputTuple,
      AllowedOutTokenSetEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "ContributionReceived(uint256,address,uint256,address,uint256,uint256,string,string,string)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "DebugApprove(address,uint256)": TypedContractEvent<
      DebugApproveEvent.InputTuple,
      DebugApproveEvent.OutputTuple,
      DebugApproveEvent.OutputObject
    >;
    DebugApprove: TypedContractEvent<
      DebugApproveEvent.InputTuple,
      DebugApproveEvent.OutputTuple,
      DebugApproveEvent.OutputObject
    >;

    "DebugApproveReset(address,uint256)": TypedContractEvent<
      DebugApproveResetEvent.InputTuple,
      DebugApproveResetEvent.OutputTuple,
      DebugApproveResetEvent.OutputObject
    >;
    DebugApproveReset: TypedContractEvent<
      DebugApproveResetEvent.InputTuple,
      DebugApproveResetEvent.OutputTuple,
      DebugApproveResetEvent.OutputObject
    >;

    "DebugContributionRecorded(uint256)": TypedContractEvent<
      DebugContributionRecordedEvent.InputTuple,
      DebugContributionRecordedEvent.OutputTuple,
      DebugContributionRecordedEvent.OutputObject
    >;
    DebugContributionRecorded: TypedContractEvent<
      DebugContributionRecordedEvent.InputTuple,
      DebugContributionRecordedEvent.OutputTuple,
      DebugContributionRecordedEvent.OutputObject
    >;

    "DebugDecodedDonate(uint256,string,string)": TypedContractEvent<
      DebugDecodedDonateEvent.InputTuple,
      DebugDecodedDonateEvent.OutputTuple,
      DebugDecodedDonateEvent.OutputObject
    >;
    DebugDecodedDonate: TypedContractEvent<
      DebugDecodedDonateEvent.InputTuple,
      DebugDecodedDonateEvent.OutputTuple,
      DebugDecodedDonateEvent.OutputObject
    >;

    "DebugDonationBegin(uint256,address,address,uint256)": TypedContractEvent<
      DebugDonationBeginEvent.InputTuple,
      DebugDonationBeginEvent.OutputTuple,
      DebugDonationBeginEvent.OutputObject
    >;
    DebugDonationBegin: TypedContractEvent<
      DebugDonationBeginEvent.InputTuple,
      DebugDonationBeginEvent.OutputTuple,
      DebugDonationBeginEvent.OutputObject
    >;

    "DebugGasFee(address,address,uint256,uint256,uint256)": TypedContractEvent<
      DebugGasFeeEvent.InputTuple,
      DebugGasFeeEvent.OutputTuple,
      DebugGasFeeEvent.OutputObject
    >;
    DebugGasFee: TypedContractEvent<
      DebugGasFeeEvent.InputTuple,
      DebugGasFeeEvent.OutputTuple,
      DebugGasFeeEvent.OutputObject
    >;

    "DebugGatewayWithdraw(address,uint256,bool)": TypedContractEvent<
      DebugGatewayWithdrawEvent.InputTuple,
      DebugGatewayWithdrawEvent.OutputTuple,
      DebugGatewayWithdrawEvent.OutputObject
    >;
    DebugGatewayWithdraw: TypedContractEvent<
      DebugGatewayWithdrawEvent.InputTuple,
      DebugGatewayWithdrawEvent.OutputTuple,
      DebugGatewayWithdrawEvent.OutputObject
    >;

    "DebugOnCallEntered(bytes,uint256,address,uint256)": TypedContractEvent<
      DebugOnCallEnteredEvent.InputTuple,
      DebugOnCallEnteredEvent.OutputTuple,
      DebugOnCallEnteredEvent.OutputObject
    >;
    DebugOnCallEntered: TypedContractEvent<
      DebugOnCallEnteredEvent.InputTuple,
      DebugOnCallEnteredEvent.OutputTuple,
      DebugOnCallEnteredEvent.OutputObject
    >;

    "DebugOnRevert(address,uint256,bytes)": TypedContractEvent<
      DebugOnRevertEvent.InputTuple,
      DebugOnRevertEvent.OutputTuple,
      DebugOnRevertEvent.OutputObject
    >;
    DebugOnRevert: TypedContractEvent<
      DebugOnRevertEvent.InputTuple,
      DebugOnRevertEvent.OutputTuple,
      DebugOnRevertEvent.OutputObject
    >;

    "DebugRouterMissing()": TypedContractEvent<
      DebugRouterMissingEvent.InputTuple,
      DebugRouterMissingEvent.OutputTuple,
      DebugRouterMissingEvent.OutputObject
    >;
    DebugRouterMissing: TypedContractEvent<
      DebugRouterMissingEvent.InputTuple,
      DebugRouterMissingEvent.OutputTuple,
      DebugRouterMissingEvent.OutputObject
    >;

    "DebugRouterSet(address)": TypedContractEvent<
      DebugRouterSetEvent.InputTuple,
      DebugRouterSetEvent.OutputTuple,
      DebugRouterSetEvent.OutputObject
    >;
    DebugRouterSet: TypedContractEvent<
      DebugRouterSetEvent.InputTuple,
      DebugRouterSetEvent.OutputTuple,
      DebugRouterSetEvent.OutputObject
    >;

    "DebugSwapFailed(string)": TypedContractEvent<
      DebugSwapFailedEvent.InputTuple,
      DebugSwapFailedEvent.OutputTuple,
      DebugSwapFailedEvent.OutputObject
    >;
    DebugSwapFailed: TypedContractEvent<
      DebugSwapFailedEvent.InputTuple,
      DebugSwapFailedEvent.OutputTuple,
      DebugSwapFailedEvent.OutputObject
    >;

    "DebugSwapFailedBytes(bytes)": TypedContractEvent<
      DebugSwapFailedBytesEvent.InputTuple,
      DebugSwapFailedBytesEvent.OutputTuple,
      DebugSwapFailedBytesEvent.OutputObject
    >;
    DebugSwapFailedBytes: TypedContractEvent<
      DebugSwapFailedBytesEvent.InputTuple,
      DebugSwapFailedBytesEvent.OutputTuple,
      DebugSwapFailedBytesEvent.OutputObject
    >;

    "DebugSwapPlanned(address,address,uint256,uint256)": TypedContractEvent<
      DebugSwapPlannedEvent.InputTuple,
      DebugSwapPlannedEvent.OutputTuple,
      DebugSwapPlannedEvent.OutputObject
    >;
    DebugSwapPlanned: TypedContractEvent<
      DebugSwapPlannedEvent.InputTuple,
      DebugSwapPlannedEvent.OutputTuple,
      DebugSwapPlannedEvent.OutputObject
    >;

    "DebugSwapSucceeded(uint256)": TypedContractEvent<
      DebugSwapSucceededEvent.InputTuple,
      DebugSwapSucceededEvent.OutputTuple,
      DebugSwapSucceededEvent.OutputObject
    >;
    DebugSwapSucceeded: TypedContractEvent<
      DebugSwapSucceededEvent.InputTuple,
      DebugSwapSucceededEvent.OutputTuple,
      DebugSwapSucceededEvent.OutputObject
    >;

    "DebugToggle(bool)": TypedContractEvent<
      DebugToggleEvent.InputTuple,
      DebugToggleEvent.OutputTuple,
      DebugToggleEvent.OutputObject
    >;
    DebugToggle: TypedContractEvent<
      DebugToggleEvent.InputTuple,
      DebugToggleEvent.OutputTuple,
      DebugToggleEvent.OutputObject
    >;

    "DebugTransferOut(address,address,uint256)": TypedContractEvent<
      DebugTransferOutEvent.InputTuple,
      DebugTransferOutEvent.OutputTuple,
      DebugTransferOutEvent.OutputObject
    >;
    DebugTransferOut: TypedContractEvent<
      DebugTransferOutEvent.InputTuple,
      DebugTransferOutEvent.OutputTuple,
      DebugTransferOutEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Rescue(address,address,uint256)": TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;
    Rescue: TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;

    "SlippageUpdated(uint256)": TypedContractEvent<
      SlippageUpdatedEvent.InputTuple,
      SlippageUpdatedEvent.OutputTuple,
      SlippageUpdatedEvent.OutputObject
    >;
    SlippageUpdated: TypedContractEvent<
      SlippageUpdatedEvent.InputTuple,
      SlippageUpdatedEvent.OutputTuple,
      SlippageUpdatedEvent.OutputObject
    >;
  };
}
